### ISSUE TITLE
[SUB-EPIC] Dependency Management

### ISSUE THREAD

**Issue by ls-1801** [nebulastream/nebulastream#176]
### Description

We want to implement our new Dependency Management System using vcpkg as described in the [design document](https://github.com/nebulastream/nebulastream-public/blob/master/docs/design/20240710_dependency-management.md).

### Acceptance Criteria

- [x] All dependencies are tracked by the local vcpkg manifest
- [x] CMake Build Configuration chooses different modes according to the design document. Local vcpkg, ad-hoc vcpkg creation, based on environment variable for docker container
- [x] CI can build the project + tests
- [x] CI can build dependency images
```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/177
- [ ] https://github.com/nebulastream/nebulastream-public/issues/178
- [ ] https://github.com/nebulastream/nebulastream-public/issues/179
- [ ] https://github.com/nebulastream/nebulastream-public/issues/189
- [ ] https://github.com/nebulastream/nebulastream-public/issues/228
```
