### ISSUE TITLE
[SUB-EPIC] Create Docker Images for building and running NebulaStream

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#22]
#### Docker Images for non-Linux development environments
Instead of offering native support for non-Linux Operating Systems, we should provide a Docker Image that contains the required software to build the standalone worker (Not sure about future Plugins) on non-Linux machines. We already have several docker images on ducker hub. 

#### Executable Image for distribution
We should distribute Docker Images for:
- Current Stable Version: No Brainer
- Current Unstable/Nightly/Master: Regression Tests for determining stability

We should distribute multiple versions:
- Hardened debug build: To catch runtime errors during Testing.
- Optimized build: Everyday usage 
- Benchmark build: Disables debug logging at compile time 

_Edited from https://github.com/nebulastream/nebulastream-public/discussions/2#discussioncomment-9652745_

### Possible Issues / Steps
1. Check out what different docker images we create and if docker/README.md is still up-to-date.
2. Decide what docker images to keep and what to add
3. Get rid of the macOS CI
4.  Write/Update docker files 
    - Add GDB and Ninja (`ninja-build`)  (Personal note)
```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/91
- [ ] https://github.com/nebulastream/nebulastream-public/issues/92
- [ ] https://github.com/nebulastream/nebulastream-public/issues/137
```
