### ISSUE TITLE
[SUB-EPIC] Enhance CI Runs with Automatic Check

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#23]
### CI Runs 
Currently, we run our CI per PR and after every merge into the main branch and create a new release. This in turn triggers an additional CI run.

The current idea is to have three versions.
1. Stable version (with a release number)
2. Nightly version (current main branch if it changed) for stability tests.
3. Fast tests for every PR. In this run, we also check for the test coverage and coding guidelines.

### Test Coverage Checks
We decided to use what we already have in our project, which is https://github.com/irongut/CodeCoverageSummary. Additionally, we said that if the test coverage is worse than before, we do not allow the PR to be merged (we might have to delete this in the beginning of this milestone).

### Coding Guidelines and Code Format
We already run a check of our code format and guard check via `docker/buildImage/entrypoint-nes-build-format-check.sh` and `docker/buildImage/entrypoint-nes-build-guard-check.sh`. 
For the code format, we might have to  change the `format-check` script depending on the outcome of the poll [Clang-Format](https://github.com/nebulastream/nebulastream-public/discussions/14#discussion-6807082).
For the coding guidelines, we have to create a new script and call it similar to the existing ones. What coding guidelines we follow and what we check there depends on the outcome of the polls [Code-Style Forward Declarations](https://github.com/nebulastream/nebulastream-public/discussions/19#discussion-6807720) and [Code-Style - Comments](https://github.com/nebulastream/nebulastream-public/discussions/18#discussion-6807488).

#### Release
A release is created after reaching a stable version after/before reaching a Milestone. We decided to manually trigger a release.

#### PR
The CI should not add additional commits for general PR Merges. It is also not necessary if we enforce Code-Formatting during the PR and the version is only bumped at a release.

_Edited from https://github.com/nebulastream/nebulastream-public/discussions/2#discussioncomment-9647130 and https://github.com/nebulastream/nebulastream-public/discussions/2#discussioncomment-9647165_

### Possible Issues / Steps
1. Take a look and see what we can take from the current github workflow files.
2. Adapt/Create new workflow files to support the three CI runs (Every PR/Fast Tests, Nightly, Release)
    1. Add the test coverage to every pr run 
    2. Add coding checks to every pr run
4. Write README similar to `docker/README` about each github workflow file.
```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/98
- [ ] https://github.com/nebulastream/nebulastream-public/issues/100
- [ ] https://github.com/nebulastream/nebulastream-public/issues/107
- [ ] https://github.com/nebulastream/nebulastream-public/issues/138
- [ ] https://github.com/nebulastream/nebulastream-public/issues/99
- [ ] https://github.com/nebulastream/nebulastream-public/issues/154
- [ ] https://github.com/nebulastream/nebulastream-public/issues/132
- [ ] https://github.com/nebulastream/nebulastream-public/pull/231
```
