### ISSUE TITLE
[Epic] Reimplement Data Source

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream#237]
### Description

After finishing the source/sink refactoring (#69), we should reimplement the DataSource for the following reasons:
- each DataSource occupies a thread, if we want to support hundreds of sources on a single worker, this does not scale well
- each DataSource receives a local buffer manager with a fixed number of available buffers, this can potentially dead lock the task queue, if sources occupy all buffers and operators cannot progress anymore, because no more buffers are available
- there is still legacy error handling in the DataSources that we should rethink; we should agree on a formal approach that describes how DataSources behave, including disconnects, end of files/streams, stop (user request or internal), timeouts, etc.
- we removed the option to share sources during #69, we should reintroduce the logic

### Acceptance Criteria

Theoretical:
- [ ] 1) develop a concept for how to perform data ingestion multi-threaded for all DataSources without consuming more than a fixed number of threads and without requiring more than a fixed number of buffers
- [ ] 2) develop a formal approach to handle errors, stop requests, end of files, timeouts, etc.
- [ ] 3) develop a high-level solution for how to perform source sharing, based on 1) and 2).

Practical:
- [ ] implement new DataSource, using the solution to 2).
- [ ] implement source sharing into the new DataSource, based on the solution for 3)
- [ ] write dedicated source tests (most certainly sub-epic) that can test arbitrary sources, allowing our System level tests to mostly operate using CSVSources (because we know other sources function in general). Nightly tests should then probe for bugs that are caused by source configurations, affecting overall query behavior.
