### ISSUE TITLE
[SUB-EPIC] Integrating Nautilus Lib and some Nautilus-Operators

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#25]
### Nautilus Update
After some discussion, @alepping and myself plan on importing the [nautilus lib](https://github.com/nebulastream/nautilus/) into NebulaStream. We know that we have to refactor/adapt the nautilus operators but the advantages outweigh the cost of it. We can get help from Philipp for the integration.

_Originally posted by @keyseven123 in https://github.com/nebulastream/nebulastream-public/discussions/1#discussioncomment-9764281_

### Nautilus Operators 
Before we have to touch almost all operators, we should get rid of some operators / operator variants that are not tested or we have a better version in our system. The goal is to have the same functionality of operators at the end of the milestone but with the new nautilus lib/version as well as cleaner and better documented operators. 
We remove at least the following operators:
- Bucketing for Aggregation and Join
- All Hash-Join Variants except for the Thread-Local-Late-Merge
- Bloomfilter
- ModelInferance and UDF Operators
- Batchoperators
- StatisticBuildOperators

An additional point is that we should only use `getBufferNoBlocking()` to avoid deadlocks due to no buffers being available and all workers are waiting on receiving one. We should also investigate, if we can maybe give the `PipelineExecutionContext` a `BufferProvider` that only allows to get buffers in a non-blocking way.

_As discussed in https://github.com/nebulastream/nebulastream-public/discussions/1#discussioncomment-9654304 and https://github.com/nebulastream/nebulastream-public/discussions/4#discussioncomment-9654376_

### Possible Issues / Steps
The integration of the new nautilus lib will make all operators unusable at first. To be able to not have gigantic PRs, we came up with the following idea.
Therefore, we will first try to get a simple filter query with an equal and non-equal expression/function. 
After we have a filter operator running, we will port the remaining operators and functions.

```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/101
- [ ] https://github.com/nebulastream/nebulastream-public/issues/102
- [ ] https://github.com/nebulastream/nebulastream-public/issues/103
- [ ] https://github.com/nebulastream/nebulastream-public/issues/104
- [ ] https://github.com/nebulastream/nebulastream-public/issues/106
- [ ] https://github.com/nebulastream/nebulastream-public/issues/264
- [ ] https://github.com/nebulastream/nebulastream-public/issues/351
```
