### ISSUE TITLE
[SUB-EPIC] General Code Cleanup

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#26]
### Description

In several of our discussions and by looking through our code, there are several smaller issues and cleanup duties to be performed by us. One idea is that this EPIC creates issues that are a good starting point for people not deeply familiar to the general code. To have not large PRs, we tackle this folder by folder.

### Steps / Things to do
The following come to mind in no particular order
1. Replace java-like methods, such as `toString()`, `equal()`, `isIdentical()`, ... with the correct operator overloading.
    - We might also disallow in our code format check  (see #23 ), depending on how fast we get our issues done.
2. Use C++ style and syntax in our code wherever possible: 
    -  `auto`
    - Separate CPP and HPP files
    - Pass Objects as (const) reference wherever (not as shared ptr and not via copy)
4. Increase our overall test coverage by adding unit and execution test.
5. Group parameters of methods into a struct for better readability and ease of use, e.g., 
```
ConvertLogicalToPhysicalSource::createDataSource(OperatorId operatorId,
                                                 OriginId originId,
                                                 StatisticId statisticId,
                                                 const SourceDescriptorPtr& sourceDescriptor,
                                                 const Runtime::NodeEnginePtr& nodeEngine,
                                                 size_t numSourceLocalBuffers,
                                                 const std::vector<Runtime::Execution::SuccessorExecutablePipeline>& successors)
```
could be also written as 

```
ConvertLogicalToPhysicalSource::createDataSource(const TupleBufferMetaData& tupleBufferMetaData,
                                                 const SourceDescriptorPtr& sourceDescriptor,
                                                 const Runtime::NodeEnginePtr& nodeEngine,
                                                 const std::vector<Runtime::Execution::SuccessorExecutablePipeline>& successors)```
```
------------------

```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/191
- [ ] https://github.com/nebulastream/nebulastream-public/pull/196
- [ ] https://github.com/nebulastream/nebulastream-public/issues/197
- [ ] https://github.com/nebulastream/nebulastream-public/pull/160
- [ ] https://github.com/nebulastream/nebulastream-public/issues/238
- [ ] https://github.com/nebulastream/nebulastream-public/issues/239
- [ ] https://github.com/nebulastream/nebulastream-public/issues/312
- [ ] https://github.com/nebulastream/nebulastream-public/issues/349
- [ ] https://github.com/nebulastream/nebulastream-public/issues/368
- [ ] https://github.com/nebulastream/nebulastream-public/issues/449
```

**Comment by alepping** [comment]
Discussed with @keyseven123. Was addressed by many smaller issues and is done.
