### ISSUE TITLE
[SUB-EPIC] PipelineExecutionContext and WorkerContext

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#27]
## Problems
1. Currently, the PEC is created during query compilation (LowerToExecutableQueryPlanPhase). The context is instantiated with Lambdas to implement the `emitBuffer`, `dispatchBuffer` functions, but this means that we have to drag the QueryManager, BufferManager through the whole compilation phase.
2. The PEC implements the TupleBuffer chunking logic, which should be moved to the `EmitOperator`. We want to use the OperatorHandlers to store state of an operator instead of using many components in the system for different purposes.
3. OperatorHandlers are accessed via the pipeline execution context, which means the QueryManager knows about OperatorHandlers
4. The ThreadID is accessed via the WorkerContext, which we plan to remove entirely (at least not known to the query-compiler)

## Proposal
The PEC has no business being instantiated within query compilation. Instead, a PEC should be constructed within the WorkerThread calling the PipelineStage; thus, it should be cheap to construct.

```c++
ExecutionResult Task::operator()(WorkerContextRef workerContext) {
    try {
        if (auto* executablePipeline = std::get_if<Execution::ExecutablePipelinePtr>(&pipeline)) {
            PipelineExecutionContext pipelineExecutionContext(*bufferManager, workerContext.getThreadId());
            return (*executablePipeline)->execute(buf, pipelineExecutionContext);
        }
```
The PEC should be limited to: 
- `emitBuffer`
- `dispatchBuffer` functions
- giving access to the BufferManager. 
- Thread Information, e.g., what thread calls the PEC

```mermaid
classDiagram

PipelineExecutionContext <|-- PipelineExecutionContextImpl: Is-a
PipelineExecutionContext <|-- MockedPipelineExecutionContext: Is-a
PipelineExecutionContext <-- NautilusExecutablePipelineStage: Uses
MockedPipelineExecutionContext <.. NautilusExecutablePipelineStage: Uses for internal testing
PipelineExecutionContextImpl <.. NautilusExecutablePipelineStage: When executed in the runtime

namespace ExecutionInterfaces {
    class PipelineExecutionContext{
        <<Interface>>
        +emitBuffer(TupleBuffer) void
        +dispatchBuffer(TupleBuffer) void
        +getThreadId() ThreadId
        +getBufferProvider() AbstractBufferProvider
    }
}

namespace Runtime {
    class PipelineExecutionContextImpl{
        +emitBuffer(TupleBuffer) void
        +dispatchBuffer(TupleBuffer) void
        +getThreadId() ThreadId
        +getBufferProvider() AbstractBufferProvider
        -AbstractBufferProviderPtr bufferProvider
        -ThreadId threadId
        -ExecutablePipelinePtr: nextPipeline
        -QueryManagerPtr: qm
    }
}

namespace Query-Compiler {
    class NautilusExecutablePipelineStage {
        +execute(TupleBuffer&, PipelineExecutionContext&)
        +setup(PipelineExecutionContext&)
        +stop(PipelineExecutionContext&)
    }

    class MockedPipelineExecutionContext {
        +emitBuffer(TupleBuffer) void
        +dispatchBuffer(TupleBuffer) void
        +getThreadId() ThreadId
        +getBufferProvider() AbstractBufferProvider
    }
}
```

_Edited from https://github.com/nebulastream/nebulastream-public/discussions/4#discussioncomment-9707590_

### Possible Steps
1. Remove buffering of tuple buffers of the `WorkerContext`
2. Create new interface and move all of the implementation into an `PipelineExecutionContextImpl`
3. Use `MockedPipelineExecutionContext` for all of our tests
[tasklist]
### Tasks
- [x] https://github.com/nebulastream/nebulastream-public/issues/78
- [x] https://github.com/nebulastream/nebulastream-public/issues/79
- [x] https://github.com/nebulastream/nebulastream-public/issues/80
- [x] https://github.com/nebulastream/nebulastream-public/issues/81
- [ ] https://github.com/nebulastream/nebulastream-public/issues/82
- [ ] https://github.com/nebulastream/nebulastream-public/issues/83
- [x] https://github.com/nebulastream/nebulastream-public/issues/87
