### ISSUE TITLE
[SUB-EPIC] Remove unused components in NodeEngine

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#28]
### Remove not being used/integrated components
There are several components that are not actively being used and we should remove the following components:
- Statistics
- Monitoring
- BloomFilter
- HardwareManager
- MultiQueueQueryManager

_Edited from https://github.com/nebulastream/nebulastream-public/discussions/4#discussioncomment-9654376_
```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/97
- [ ] https://github.com/nebulastream/nebulastream-public/issues/96
- [ ] https://github.com/nebulastream/nebulastream-public/issues/95
- [ ] https://github.com/nebulastream/nebulastream-public/issues/94
- [ ] https://github.com/nebulastream/nebulastream-public/issues/93
- [ ] https://github.com/nebulastream/nebulastream-public/issues/181
```
