### ISSUE TITLE
[SUB-EPIC] Moving OperatorHandlers into the NautilusExecutablePipelineStage

### ISSUE THREAD

**Issue by ls-1801** [nebulastream/nebulastream#30]
### Description

Currently, the OperatorHandlers are created during lowering to physical operators and passed to the lowering to nautilus.

After discussing this with @PhilippGrulich and @keyseven123, we concluded that operator handlers should be an implementation detail for the Nautilus operator and should not be exposed to other system components.

We keep operator handlers at the physical level to give all relevant operators access to the global operator state (accessed via an OperatorHandler) 

OperatorHandlers were previously accessed through the PipelineExecutionContext (PEC). This issue tracks the integration of the access to operator handlers via static memory access within the generated operator.

During Lowering, we emit the address of the heap-allocated operator handler to the tracing context. We guarantee that the pointer is always valid by:
1. Allocating on the Heap
2. Managing the lifetime of the OperatorHandler through a shared pointer in the the owinging pipeline.

### Use case/motivation

We want to reduce the interface between runtime and query lowering.
OperatorHandlers have previously been exposed to the runtime, especially due to the runtime reconfigurability interface. However, we will pursue actions required for operator state serialization using other mechanisms, possibly controlled by the owning pipeline.

When creating the PEC the runtime does not need information about operator handlers, thus the context can be easily constructed with local information of the worker thread.

### Related issues

#27

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/nebulastream/nebulastream/blob/master/CODE_OF_CONDUCT.md)

```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/78
```

**Comment by alepping** [comment]
@keyseven123 and @ls-1801 is this still relevant?
