### ISSUE TITLE
[SUB-EPIC] Redesign SingleNodeWorker

### ISSUE THREAD

**Issue by ls-1801** [nebulastream/nebulastream#34]
### Fully Specified Logical Query Plan (FS-LQP)

Is a plan of `Logical Operators`, `Source Descriptors` and `Sink Descriptors` which passed all logical transformations.

- Logical Optimizations have been performed
- Schema Inference has been performed: Every Operator knows its input and output Schema
- `OriginIds` have been propagated
- All Descriptors are `Physical`

### Executable Query Plan

Is a plan of `ExecutablePipelines`, `Source Descriptors` and `Sink Descriptors`
- Pipeline to Pipeline connections (`next`)
- Since `Sources` do not exist yet, mapping from `SourceDescriptor` to its successor is only tracked loosely in a mapping
- `SinkDescriptors` are mapped to its predecessors

```mermaid
flowchart LR
 S1([SourceDesc1])
 S2([SourceDesc2])

    
 O1[Operator 1]
 O2[Operator 2]
 O3[Join]

 s1([SinkDesc1])
 s2([SinkDesc2])

    
 S1 -..-> O1
 S2 -..-> O2
 O1 --next--> O3
 O2 --next--> O3

 O2 ~~~ s1
 s1 -..-> O2
    
 O3 ~~~ s2
 s2 -..-> O3
```

### Instantiated Query Plan

The Instantiated Query Plan contains concrete `Sources` and `Sinks`. `Sources` are instructed to emit to successor Operators via an `EmitFunction` which is injected into the `Source` during instantiation. The mapping from Sinks to their predecessor within the `Executable Query Plan` is used to patch `next` pointers of its predecessors. The Sink itself will be a `Executable Pipeline Stage` wrapped in a `Executable Pipeline` (just like the other Operators). An `Instantiated Query Plan` does not indicate that the Data Sources are running, it is created during query registration. During query startup, the instantiated query plan can start its data sources and stop them during query shutdown.

```mermaid
flowchart LR
 S1(Source1)
 S2(Source2)

    
 O1[Operator 1]
 O2[Operator 2]
 O3[Join]

 s1[Sink1]
 s2[Sink2]
    
 S1 ==Emit Function==> O1
 S2 ==Emit Function==> O2
 O1 --next--> O3
 O2 --next--> O3
 O2 --next--> s1
 O3 --next--> s2        
        
```

## Single Node Worker
We describe the Interfaces relevant for the Single-Node-Milestone. An external user should be able to:

1. Start a Query
2. Stop a Query
3. Retrieve the Query Status

### Worker

For the first milestone the Worker is merly responsible for:
- Owning the `QueryCompiler` and `QueryManager`. Including constructing and configuring them on system startup.
- Serving the GRPC Interface and delegating to the `QueryCompiler` and `QueryManager`
- Tracking/Logging the State of Queries using the `QueryLifeCycleStatusListener`

### GRPCInterface
We expose a GRPC interface to the user. The interface expects a FS-LQP supplied by the user. For the initial milestone we push the logic of creating a FS-LQP to the user (or a client). We do not explicitly allow dedicated query registration and query start request, rather everything will be handled by a single start request.

```mermaid
classDiagram
class GRPCWorker {
 <<interface>>
 +startQuery(FS-LQP) QueryId
 +stopQuery(QueryId)
 +queryStatus(QueryId) QueryStatus
}
```

### StatusListener
Internally the Worker tracks the status of queries by listening the Events within the QueryManager. Events are exposed with the `QueryLifecycleListener` which can be implemented by the Worker. The QueryManager will emit QueryLifeCycle Events when appropriate (e.g. when a query fails). Requests to the `queryStatus(QueryId)` can thus be handled by the Worker Node.

```mermaid
classDiagram
class QueryLifecycleListener {
 <<interface>>
 +onRegister(QueryId)
 +onStart(QueryId)
 +onStop(QueryId)
 +onFailure(QueryId, Error)
}
```

### QueryManager
```mermaid
classDiagram
class QueryManager {
 +QueryManager(Configuration)
 +~QueryManager()

 +registerListener(QueryLifeCycleListener)
 +registerQuery(ExecutableQueryPlan): QueryId
 +unregisterQuery(QueryId)
 +startQuery(QueryId)
 +stopQuery(QueryId, QueryTerminationType)
}
```

The QueryManagers interfaces exposes dedicated register and start methods, as we expect them to be relevant in future milestones, where actual registration and startup may be delayed by other participants in the overall system.

Internally during queryRegistration the `QueryManager` will instantiate `ExecutableQueryPlans` by constructing Sources and Sinks and transforming the `ExecutableQueryPlan` into a `InstantiatedQueryPlan`. The `InstantiatedQueryPlan` will be put into the `Stopped` queue and a `OnRegistration` event will be emitted.

`queryStart` will move the `InstantiatedQueryPlan` from the `Stopped` queue into the `Running` queue and an OnStart Event is emitted. Starting a Query entails starting all associated pipelines and data sources, we expect DataSources to be instructed with an `EmitFunction`, during instantiation.

Its important to distinguish between Start/Stop vs Pause/Resume. Stopping a Query entails all state to be remove the Query and restarting the Query starts from SequenceNumber 1. Pausing on the other hand implies a query can be resumed at a later point in time retaining all state. For the first milestone we explicitly limit the functionality to Start/Stop.

`queryStop` will move the `InstantiatedQueryPlan` from the `Running` queue into the `Stopped` queue and a `onStop` event is emitted. The method accepts a QueryTerminationType:
1. Soft: DataSources emit EoS: Operator State is Flushed (e.g. all Joins are triggered)
2. Hard: All DataSources are immediately stopped. Associated Tasks are skipped

`unregisterQuery` removes the query from the `Stopped` queue and completely destructs the `ExecutablePipelineStages` (including `Sinks`) and `Sources`

`registerListener` allows to register a new QueryLifeCycleStatusListener, which will receive future events. (i.e. events won't be buffered)

### QueryCompiler

The `QueryCompiler` Expects a `QueryCompilationRequest`, in form of a `FS-LQP` and `QueryCompilerConfiguration`. The output of the `lower` will be an `ExecutableQueryPlan` containing `ExecutablePipelineStages`.

```mermaid
classDiagram
class QueryCompiler {
 +lower(FS-LQP, Configuration): ExecutableQueryPlan
}
```

### Flow

The single node worker implements the grpc server and delegates calls to `startQuery` to calls to `QueryCompiler::lower`, `QueryManager::registerQuery` and `QueryManager::startQuery`.
Calls to `stopQuery` are just delegated to the `QueryManager::stopQuery` and `QueryManager::unregisterQuery`.

```mermaid
classDiagram
class GRPCInterface {
 <<interface>>
 +startQuery(FS-LQP) QueryId
 +stopQuery(QueryId)
 +queryStatus(QueryId) QueryStatus
}

GRPCInterface <|-- SingleNodeWorker: implements

class SingleNodeWorker {
 +startQuery(FS-LQP) QueryId
 +stopQuery(QueryId)
 +queryStatus(QueryId) QueryStatus

 - QueryLifecycleListener listener
 - QueryManager qm
 - QueryCompiler qc
}
```

```mermaid
sequenceDiagram
box Green GRPC
actor User
participant SN as SingleNodeWorker
end
participant QLC as QueryLifeCycleListener

participant QM as QueryManager
participant QC as QueryCompiler

User ->> SN : startQuery(FS-LQP)

SN ->> QC : lower(FS-LQP)
note left of QC: Lowering + Compilation
QC -->> SN : ExecutableQueryPlan

SN ->> QM : registerQuery(ExecutableQueryPlan)
note left of QM: Instantiation of QEP
QM ->> QLC : onRegister(QueryId)
QM -->> SN : QueryId
SN -) QM : startQuery(QueryId)
note left of QM: Start Pipelines / Sources (could by async)

SN ->> User : QueryId
QM ->> QLC : onStart(QueryId)
QLC ->> SN : Track as Running
```

### Acceptance Criteria

- [ ] Single Node Application can be started and the GRPC Server is running
- [ ] Calls to the GRPC Server are delegated as described
- [ ] Tracking of State
```[tasklist]
### Tasks
- [ ] #84
- [ ] #85
- [ ] #86
- [ ] https://github.com/nebulastream/nebulastream-public/issues/116
- [ ] https://github.com/nebulastream/nebulastream-public/issues/115
- [ ] #218
```
