### ISSUE TITLE
[SUB-EPIC] Advance Test Suite to cover Query Start and Stop Exhaustively 

### ISSUE THREAD

**Issue by zeuchste** [nebulastream/nebulastream#36]
### Description

We have to check all points where a potential query start and stop can fail like:
- Buffer allocation
- Out of resouces
- and many more
- compilation error
- network error
- GRPC error

The way of doing this to write tests for everything that can go wrong for submitting a query.  This includes:

- [ ] No query interference happens thus no query start/stop has any impact on a running query
- [ ] Node shutdown removes all allocated resources. Especially we do have a flag to track buffer leakage, but this is very expensive and disabled by default.  we should think about a lightweight mechanism to detect this, also create tests for this
- [ ] The start/stop is done atomically. Thus any step that has been done has to be rolled back if a later one fails
- [ ]  If a query deletion will really release all buffers. 

### Acceptance Criteria
- no query start or stop leads to a system crash or interference with other queries
- we have tests for all possible sources of errors
