### ISSUE TITLE
[EPIC] Minimizing nes-data-types

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream#391]
### Description

# Description
The structure of our data types in `nes-data-types` offers several significant points of improvements:
1. Remove data types that we don't support, e.g., `Array`
2. Improve implementations of data types that we (want to) support, e.g., `Text`
3. Remove layers of abstraction that we don't need, i.e., everything but `DataTypes` (remove `ExecutableType`, `PhysicalType`, `ValueTypes`)
4. Refactor factories for data types. Use registry
5. Refactor serialization. Use registry
6. Refactor Schema
7. Centralized (util) functions to convert from strings to internal data type (parsing)
8. Get rid of upper/lower bound in data types

Furthermore, there are certain goals that we should discuss first, i.e., discuss if we want to define them as our goals:
G1. Specifying data types with concrete physical information, e.g., Bool(bitpacked) -> keyword: physical schema
G2. Custom (and complex) data types. NebulaStream is extensible concerning data types. It is, e.g., simple to create spatial data types like 2D/3D coordinates. This could be implemented using the registry approach and smartly reusing existing data types (e.g., an addition on a 2D coordinate is resolved to two additions on the X and Y coordinate respectively, which are both already implemented (addition on e.g., doubles))

Concerning 3., the following DrawIO document describes what the specific Types do and how/why we can remove them:
https://drive.google.com/file/d/1YfpHJX7mg9eyO7H6Y3Alanv1694vgKIO/view?usp=sharing

```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/356
- [ ] https://github.com/nebulastream/nebulastream-public/issues/414
- [ ] https://github.com/nebulastream/nebulastream-public/issues/420
- [ ] https://github.com/nebulastream/nebulastream-public/issues/472
```
