### ISSUE TITLE
[SUB-EPIC] Extending our CI for checking robustness

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#477]
### Description

In #23, we have started with adding automated checks to our CI workflows to reduce the cognitive stress reviewers have. 
In this SUB-EPIC, we would like to extend our CI to check for robustness. The following tasks must be done

- [x] Adding Kubernetes to our workflow and creating multiple Kubernetes runnners, e.g., long-running, nightly, PR, ...
- [x] Run all our CI jobs also with all optimizations enabled, i.e., `BuildType=Release`
- [x] Run our system level tests with different worker configuration, e.g. different number of worker threads or buffer manager configuration
