### ISSUE TITLE
[EPIC] Create all needed functions and operators for SIGMOD Demo

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#480]
### Description

For our SIGMOD 2025 demo, we need some additional operators, which are not 100% clear. This EPIC tracks the progress of all operators and their status in regards to the whole pipeline, from query parser down to the executable operator.

```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/263
- [ ] https://github.com/nebulastream/nebulastream-public/issues/476
- [ ] https://github.com/nebulastream/nebulastream-public/issues/105
```
