### ISSUE TITLE
[SUB-EPIC] Hardening and Robust SingleNodeWorker

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#481]
### Description

This SUB-Epic tracks all issues that are responsible to hardening our single node worker. This list might not be 100% complete right now:

- [x] Running CI jobs with sanitizers
- [x] Increase Code-Coverage from ~25% to at least 60%
- [x] Fixing any bugs that pop up during the hardening progress
