### ISSUE TITLE
[SUB-EPIC] Testing Query Validation

### ISSUE THREAD

**Issue by adrianmichalke** [nebulastream/nebulastream#484]
### Description

Currently, our system does not have a well tested query validation step. Thus, invalid queries are detected late (eg. during query compilation, schema inference or even query execution) and with for the end user difficult to understand error messages (as they expose internals).

We should create a large catalog of (system) tests, containing invalid tests. Semantical and syntactical query errors should throw exceptions early and with easy to understand error messages. 

List of sub-issues (incomplete):
- [ ] Enable 'negative' System Level Tests. E.g.:
```
SELECT * FROM invalid_schema INTO SINK;
----
ErrorCode 1111
```
- [ ] Tests for invalid source schema usage
- [ ] Tests for invalid function usage
- [ ] Combine `QueryInvalid`, `InvalidQuerySyntax`, and`UnsupportedQuery` into one https://github.com/nebulastream/nebulastream-public/pull/605#discussion_r1922032896
