### ISSUE TITLE
[SUB-EPIC] Process for taking care of a bug

### ISSUE THREAD

**Issue by keyseven123** [nebulastream/nebulastream#486]
### Description

With the next milestone and moving forward, we will detect bugs in our system. As this will happen multiple times, we should create a markdown that documents the process of taking care of a bug. Important questions are but not limited to:
- [x] Who is responsible for the first response and when?
- [x] How to determine when to fix the bug?
- [x] Who is responsible for fixing the bug?

### Acceptance Criteria

- [x] Markdown file with a documented process
