### ISSUE TITLE
[SUB-EPIC] Components should own their Configuration

### ISSUE THREAD

**Issue by ls-1801** [nebulastream/nebulastream#51]
### Description

Currently, all Configurations live in the `nes-configurations` module. This means that the configuration effectively knows about all components in the system. This also implies that removing or adding a component to the System (e.g., Moving from the SingleNodeWorker to the MultiNodeWorker) will modify the `nes-configurations` and may affect all dependent systems.

We propose to invert the dependency and allow individual components to own their configuration directly. The `nes-configuration` module only provides the necessary building blocks to specify and compose configuration options.

The following diagram depicts what a potential distribution of components could look like. The `SingleNodeWorker` Component, which is the entry point into the application, owns the `QueryCompiler` and the `NodeEngine`. Likewise, the `SingleNodeWorker` configuration owns the sub components' configuration. All configurations use the base class and functionality provided by the `nes-configuration` module. (concrete implementation details are omitted, and tracked in a different SUB-EPIC)

```mermaid
classDiagram
class Configuration

NEConfiguration --|> Configuration : Is-A
QCConfiguration --|> Configuration : Is-A
SNConfiguration --|> Configuration : Is-A

namespace SingeNodeWorker {
    class SNConfiguration
    
    class Worker {
        -grpc
        -QueryCompiler qc
        -NodeEngine ne
        +configure(SNConfiguration)
    }
}
SNConfiguration ..> Worker : uses
Worker --* QueryCompilerInstance: Has-A
Worker --* NodeEngineInstance: Has-A
SNConfiguration --* NEConfiguration : Has-A
SNConfiguration --* QCConfiguration : Has-A

namespace QueryCompiler {
    class QCConfiguration

    class QueryCompilerInstance {
        +configure(QCConfiguration)
    }
} 
QCConfiguration ..> QueryCompilerInstance : uses

namespace NodeEngine {
    class NEConfiguration

    class NodeEngineInstance {
        +configure(NEConfiguration)
    }
} 
NEConfiguration ..> NodeEngineInstance : uses


```

### Acceptance Criteria

- [ ] All relevant components only know about their specific configuration, which also contains configuration for sub-components
- [ ] During the *construction* (or usage) of components, the configuration is passed along
- [ ] The `nes-configuration` module no longer requires component-specific configuration options. (i.e, WindowingStrategy)
```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/89
- [ ] #122
```
