### ISSUE TITLE
[SUB-EPIC] Data Type Registry

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream#572]
### Description

This sub-epic is specifically addressed at @LeoRaasch.
His goal is to refactor how we construct (logical) data types. To deduplicate code and take the first step towards extensible data types.

### Acceptance Criteria

- [x] all registries use the pattern introduced in #558 
- [x] replaced the DataTypeFactory (and all uses of it) with a registry
- [ ] refactored query parsing (using (at least optionally) identifiers for data types to allow for extensibility
- [ ] scanned codebase for usages of logical data types, refactored and written down notable usages
- [ ] introduce aliases for the datatype registry
```[tasklist]
### Tasks
- [ ] https://github.com/nebulastream/nebulastream-public/issues/573
- [ ] https://github.com/nebulastream/nebulastream-public/issues/574
- [ ] https://github.com/nebulastream/nebulastream-public/issues/575
- [ ] https://github.com/nebulastream/nebulastream-public/issues/576
```
