### ISSUE TITLE
[SUB-EPIC] Separate Formatting/Parsing from Source implementations

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream#72]
### Description
Related to the EPIC #69.

Currently, parsing sources and sinks is initiated in the sources and sinks themselves. We want to establish a clear separation between sources and sinks that consume/produce data and formatters/parsers. Instead of a CSVSource, we would have a FileSource and a CSV formatter/parser.

*Additional Information:*
- We reduce the `FileSource` to a minimal version that simply processes a file as fast as possible. That is, we remove all logic to convert a `FileSource` to a stream with a specific frequency.

#### Long Term Goal
The long-term goal is make formatting/parsing part of the compiled query. However, in this SUB-EPIC, we just clearly separate the formatting/parsing logic from the sources to create the foundation for the long-term goal.
A design document on formatting/parsing will precede implementing the long-term goal.

# Acceptance Criteria
```[tasklist]
- [ ] https://github.com/nebulastream/nebulastream-public/issues/491
- [ ] https://github.com/nebulastream/nebulastream-public/issues/495
- [ ] https://github.com/nebulastream/nebulastream-public/issues/496
```
