### ISSUE TITLE
[SUB-EPIC] Integrate the Static Plugin Registry 

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream#74]
### Description
Related to the epic #69.

In #41 we introduce a static plugin registry. In #52 we explain how we can leverage the plugin registry to simplify the implementation of sources and sinks. In this issue, we integrate the plugin registry into NebulaStream. We implement plugin registries for sources and sinks and integrate them into the query processing workflow. In particular, we replace the usages of factories with usages of the source/sink registries. Additionally, we replace the currently existing source plugin registry.

- [x] create nes-sources module
- [ ] remove CSV/TCP/PhysicalSourceTypes
- [x] integrate static plugin registry into NebulaStream, remove DefaultSourceProvider
- [x] remove old source plugin registry
- [x] replace all occurrences of source/sink factories that construct sources and sinks with usages of the new source/sink plugin registries
- [ ] add support for timeout (socket) to TCP source configuration

### Use case/motivation

As explained in #52 a plugin registry can simplify the implementations of sources and sinks.

### Additional Information

There already is a source plugin registry implemented in NebulaStream. We will replace this plugin registry.

### Related issues

- #41
- #52

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/nebulastream/nebulastream/blob/master/CODE_OF_CONDUCT.md)
