### ISSUE TITLE
[SUB-EPIC] Refactor Sinks

### ISSUE THREAD

**Issue by alepping** [nebulastream/nebulastream#75]
### Description
Related to the EPIC #69 and #272.
Afer refactoring the Sources, refactor Sinks analog to Sources.

### Acceptance Criteria
- [x] create `nes-sinks` component and move all sink-specific implementation details to `nes-sinks`
- [x] implement SinkDescriptor (analog to SourceDesciptor), remove all sink-specific descriptors
- [x] implement SinkRegistry (analog to SourceRegistry), construct sinks using SinkRegistry
- [x] refactor Nebuli to handle new general SinkDescriptor (adapt query parsing, currently we construct specific sinks, e.g. `FileSinkDescriptor` in our queries)
- [x] refactor (de-)serialization of Sinks (analog to Sources)
- [x] refactor sink lowering (single SinkProvider), get rid of all other classes related to the lowering of sinks
- [x] refactor handling of sinks in pipelines (use unique pointers wherever possible)
- [x] refactor system level tests if necessary, to use the new sink implementation
